package com.repdayrise.app.ui.components

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.ui.graphics.vector.ImageVector

/** Curated icon catalogue for habits, keyed by a stable string. */
object HabitIcons {
    val all: List<Pair<String, ImageVector>> = listOf(
        "sun" to Icons.Rounded.WbSunny,
        "sunrise" to Icons.Rounded.WbTwilight,
        "moon" to Icons.Rounded.NightsStay,
        "star" to Icons.Rounded.Star,
        "heart" to Icons.Rounded.Favorite,
        "bolt" to Icons.Rounded.Bolt,
        "flame" to Icons.Rounded.LocalFireDepartment,
        "check" to Icons.Rounded.CheckCircle,
        "target" to Icons.Rounded.TrackChanges,
        "trophy" to Icons.Rounded.EmojiEvents,
        "flag" to Icons.Rounded.Flag,
        "smile" to Icons.Rounded.Mood,
        "water" to Icons.Rounded.WaterDrop,
        "coffee" to Icons.Rounded.LocalCafe,
        "food" to Icons.Rounded.Restaurant,
        "cook" to Icons.Rounded.SoupKitchen,
        "apple" to Icons.Rounded.LocalDining,
        "nosugar" to Icons.Rounded.NoFood,
        "nodrink" to Icons.Rounded.NoDrinks,
        "nosmoke" to Icons.Rounded.SmokeFree,
        "pill" to Icons.Rounded.Medication,
        "vitamin" to Icons.Rounded.Vaccines,
        "run" to Icons.Rounded.DirectionsRun,
        "walk" to Icons.Rounded.DirectionsWalk,
        "bike" to Icons.Rounded.DirectionsBike,
        "hike" to Icons.Rounded.Hiking,
        "swim" to Icons.Rounded.Pool,
        "gym" to Icons.Rounded.FitnessCenter,
        "yoga" to Icons.Rounded.SelfImprovement,
        "stretch" to Icons.Rounded.AccessibilityNew,
        "soccer" to Icons.Rounded.SportsSoccer,
        "basketball" to Icons.Rounded.SportsBasketball,
        "tennis" to Icons.Rounded.SportsTennis,
        "heartbeat" to Icons.Rounded.MonitorHeart,
        "scale" to Icons.Rounded.Scale,
        "sleep" to Icons.Rounded.Bedtime,
        "bed" to Icons.Rounded.Hotel,
        "shower" to Icons.Rounded.Shower,
        "bath" to Icons.Rounded.Bathtub,
        "skin" to Icons.Rounded.Face,
        "spa" to Icons.Rounded.Spa,
        "leaf" to Icons.Rounded.Eco,
        "plant" to Icons.Rounded.Yard,
        "pet" to Icons.Rounded.Pets,
        "book" to Icons.Rounded.MenuBook,
        "study" to Icons.Rounded.AutoStories,
        "journal" to Icons.Rounded.EditNote,
        "write" to Icons.Rounded.Edit,
        "draw" to Icons.Rounded.Draw,
        "brush" to Icons.Rounded.Brush,
        "palette" to Icons.Rounded.Palette,
        "music" to Icons.Rounded.MusicNote,
        "piano" to Icons.Rounded.Piano,
        "headphones" to Icons.Rounded.Headphones,
        "podcast" to Icons.Rounded.Podcasts,
        "camera" to Icons.Rounded.PhotoCamera,
        "language" to Icons.Rounded.Translate,
        "brain" to Icons.Rounded.Psychology,
        "idea" to Icons.Rounded.Lightbulb,
        "code" to Icons.Rounded.Code,
        "work" to Icons.Rounded.Work,
        "school" to Icons.Rounded.School,
        "news" to Icons.Rounded.Newspaper,
        "mail" to Icons.Rounded.Mail,
        "inbox" to Icons.Rounded.Inbox,
        "call" to Icons.Rounded.Call,
        "family" to Icons.Rounded.FamilyRestroom,
        "kind" to Icons.Rounded.VolunteerActivism,
        "nophone" to Icons.Rounded.MobileOff,
        "game" to Icons.Rounded.SportsEsports,
        "money" to Icons.Rounded.Savings,
        "wallet" to Icons.Rounded.AccountBalanceWallet,
        "shop" to Icons.Rounded.ShoppingBag,
        "clean" to Icons.Rounded.CleaningServices,
        "laundry" to Icons.Rounded.LocalLaundryService,
        "kitchen" to Icons.Rounded.Kitchen,
        "timer" to Icons.Rounded.Timer,
        "cake" to Icons.Rounded.Cake,
        "party" to Icons.Rounded.Celebration,
    )

    private val map: Map<String, ImageVector> = all.toMap()

    operator fun get(key: String): ImageVector = map[key] ?: Icons.Rounded.WbSunny
}
